voting_records_site/voting_record_ui/urls.py
from django.urls import path

from . import views

app_name = 'voting_record_ui'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail', views.detail, name='detail'),
    # path('<int:file_number>/results/',
    #      views.results, name='results'),
    path('search', views.search_votes, name='search'),
    path('<int:file_number>/votes/', views.get_votes, name='votes')
]

voting_records_site/voting_records_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('voting_record_ui/', include('voting_record_ui.urls')),
    path('admin/', admin.site.urls),
]

voting_records_site/voting_record_ui/models.py
from django.db import models

# Create your models here.

class MetaTable(models.Model):
    #id = models.AutoField(primary_key=True)
    file_created = models.DateTimeField('date file created')
    file_number = models.IntegerField(default = 0)
    link=models.CharField(max_length=200)
    status= models.CharField(max_length=30)
    title = models.TextField("description", null=True, blank=True)
    type=models.CharField(max_length=10)

class PassedLegislation(models.Model):
    #id = models.AutoField(primary_key=True)
    file_number = models.IntegerField(default=0)
    A_Details = models.TextField("description", null=True, blank=True)
    Action = models.TextField("action", null=True, blank=True)
    Action_By = models.CharField(max_length=100)
    Date = models.DateTimeField('date passed')
    Version = models.TextField(default='0')

class all_links(models.Model):
    #id = models.AutoField(primary_key=True)
    file_number = models.IntegerField(default=0)
    A_Details = models.TextField("description", null=True, blank=True)
    Action = models.TextField("action", null=True, blank=True)
    Action_By = models.CharField(max_length=100)
    Date = models.TextField('date passed',blank=True, null=True)
    Version = models.TextField(default='0')

class votes(models.Model):
    id = models.AutoField(primary_key=True)
    person = models.CharField(max_length=20)
    vote = models.CharField(max_length=10)
    file_number = models.IntegerField(default=0)
    #id = models.AutoField(primary_key=True)

voting_records_site/voting_record_ui/forms.py
from django import forms


class UserInput(forms.Form):
    alder = forms.CharField(help_text="Enter a Alderman Name")

    def upper_name(self):
        return self.alder.upper()

voting_records_site/voting_record_ui/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .forms import UserInput
from .models import PassedLegislation, MetaTable, votes

# Create your views here.

# def index(request):
#     file_nums = [p.file_number for p in PassedLegislation.objects.order_by('-Date')[:5]]
#     latest_file_list = [j for fn in file_nums for j in MetaTable.objects.filter(file_number=fn)]
#     #print(latest_file_list)
#     output = ', '.join([f.title for f in latest_file_list])
#     #output = ', '.join([str(MetaTable.objects.get(file_number = f.file_number)) for f in latest_file_list])
#     print(output, 'THIS IS OUTPUT')
#     #loader.get_template('voting_record_ui/index.html')
#     context = {'latest_file_list': latest_file_list}
#         #return HttpResponse(template.render(context, request))
#     return render(request, 'voting_record_ui:index.html', context)




def search_votes(request):
    '''
    search news form page
    '''

    if request.method == 'POST':

        form = UserInput(request.POST)
        print(form.data)
        #alder = form.data['alder'].upper_name()

        if form.is_valid():
            HttpResponse('Thank you we are processing your request')
    else:
        form = UserInput()
    return render(request, 'voting_record_ui/search.html', {'form':form})


def detail(request):

    # try:
    #     file_record = MetaTable.objects.sget(file_number = file_number)
    # except MetaTable.DoesNotExist:
    #     raise Http404("File number does nto exist")

    #file_record = get_object_or_404(MetaTable, file_number = file_number)
    form = UserInput(request.POST)
    alder =  form.data['alder'].upper()
    print(alder)
    vote_records = votes.objects.filter(person=alder)
    for v in vote_records:
        print(v.vote)
    file_metas = [(MetaTable.objects.get(file_number=f.file_number), f.vote) for f in vote_records]
    print(file_metas)
    #print(file_record, file_record.file_number)
    #return render(request, 'voting_record_ui/detail.html', {'file_record': file_record,})
    return render(request, 'voting_record_ui/detail.html', {'vote_records': vote_records, 'file_metas':file_metas, 'alder':alder})
    #return HttpResponse("You're looking at file number %s." % file_number)

# def results(request, file_number):
#     response= "You're looking at the description of file number %s."
#     return HttpResponse(response % file_number)

def get_votes(request, file_number):
    #return HttpResponse("The Alder people voted in the following way on file_number %s." % file_number)
    
    #print(file_record, 'HI LINE 48')
    try:
        selected_choice = PassedLegislation.objects.filter( file_number=file_number)
        file_record = get_object_or_404(MetaTable, file_number=file_number)
        print(file_number)
        return render(request, 'voting_record_ui/results.html', {'file_title':file_record.title, 'selected_choice': selected_choice})

    except (KeyError, PassedLegislation.DoesNotExist):
        return render(request, 'voter_record_ui/detail.html', {
            'file_record':file_record,
            'error_message':"You didn't select a valid choice.",
        })

# def results(request, file_number):
#     print(file_record, "HI 54")
#     file_record = get_object_or_404(votes, file_number=file_number)
#     #print(file_record, "HI 54")
#     return render(request, 'voting_record_ui:results.html', {'file_record': file_record})


class IndexView(generic.ListView):
    template_name = 'voting_record_ui/index.html'
    context_object_name = 'latest_file_list'

    def get_queryset(self):
        """Return the last five published questions."""
        file_nums = [
            p.file_number for p in PassedLegislation.objects.order_by('-Date')[3000:3005]]
        latest_file_list = [j for fn in file_nums for j in MetaTable.objects.filter(file_number=fn)]

        return latest_file_list


# class DetailView(generic.DetailView):
#     model = MetaTable
#     template_name = 'voting_record_ui/detail.html'
#     slug_url_kwarg='file_number'


# class ResultsView(generic.DetailView):
#     model = votes
#     template_name = 'voting_record_ui/results.html'
    #slug_url_kwarg = 'file_number'

voting_records_site/voting_record_ui/templates/voting_record_ui/detail.html
<!-- {{ file_number }} -->

<!-- <h1>{{ file_record.file_number }}</h1>
<ul>
{% for choice in file_record.choice_set.all %}
    <li>{{ choice.choice_text}}</li>
{% endfor %}
</ul> -->

<h1>{{ alder }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<table>
    <tr>
        <th>'Ordinance Description'</th>
        <th>'Vote'</td>
    </tr>
{% if file_metas %}
    {% for f1,f2 in file_metas %}
    <tr>
        
        <td><a href="{% url 'voting_record_ui:votes' f1.file_number %}">{{ f1.title }}</a></td>
        <td>{{ f2 }}</td>
        
    </tr>
    {% endfor %}
{% else %}
    <p> No votes are available.</p>
{% endif %}
</table>

voting_records_site/voting_record_ui/templates/voting_record_ui/detail_old.html
{#<form action="{% url 'voting_record_ui:votes' file_record.file_number %}" >
    {% csrf_token %}

    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.file_number}}">
    <label for="choice{{ forloop.counter }}">{{ file_record.title}}</label><br>
    <input type="submit" value="Votes">
</form> #}

voting_records_site/voting_record_ui/templates/voting_record_ui/index.html
{% if latest_file_list %}
    <ul>
    {% for f in latest_file_list %}
        <li><a href="{% url 'voting_record_ui:detail' f.file_number %}">{{ f.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No polls are available.</p>
{% endif %}

voting_records_site/voting_record_ui/templates/voting_record_ui/results.html
<h1>{{ file_number }}</h1>

<ul>
    {% for vote in selected_choice %}
    <li>{{ vote.person }} -- {{ vote.vote }}</li>
    {% endfor %}
</ul>

voting_records_site/voting_record_ui/templates/voting_record_ui/search.html
{% block content %}
<div class="jumbotron text-center">
    <div class="container">
        <h1>Voting Record Lookup Project </h1>
        <p style='color:white'>Choose an Alderperson and we will display the voting record <p>
    </div>
</div>
<div class="container">

    <form action="detail" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
        
    </form>
</div>
{% endblock %}